---
title: "QP Data Analysis"
author: "Diana Sanchez"
date: "January 2023"
output:
  html_document: default
  word_document: default
---


rm(list = ls(all.names = TRUE)) #clear R environment


# Load libraries
```{r message=FALSE, warning=FALSE , include=FALSE,echo =TRUE}
library(readr)
library(ggplot2)
library(GGally)
library(speakr)
library(dplyr)
library(tidyverse)
library(readr)
library(plyr)
library(stringi)
library(purrr)
library(broom)
library(scatterplot3d)
library(table1)

library(tidyr)
library(readr)
library(readxl)

library(patchwork)
```



#Analysis of all_data 
## Tidy all_data
all_data df includes all 58 participants, two groups. Only total correct responses are included for each experimental task (flanker, stroop, backward). new_all_data excludes participant kbzo0 who was removed.
```{r message=FALSE, warning=FALSE , include=FALSE,echo =TRUE}
#Load working data
all_data <- read.csv("/Users/princesa/Desktop/diana/all_data.csv", header = TRUE)

#summary
summary(all_data)

#remove outlier No.45 (kbzo7)
new_all_data <- all_data[-c(45),]

#separate groups: nonLanguage teachers and language teachers
nonLanguage <- new_all_data[1:36, ]
language <- new_all_data[37:57, ]

nonLanguage$language = "NonLanguage" #add column "language" to indicate nonlanguage
language$language = "Language" #add column "language" to indicate language

#adding "language" column to indicate nonLanguage or language for each participant in all_data
new_all_data = bind_rows(nonLanguage,language)
```


##Standardize Age and IQ
```{r}
final_df = new_all_data %>% mutate(group_language = if_else(language == 'NonLanguage',-1,1),
            age_z = (age - mean(age)) / sd(age),
            iq_z = (IQ - mean(IQ)) / sd(IQ))
final_df
```

```{r}
m1 = lm(stroop_correct ~ language + age + IQ, final_df)
summary(m1)

par(mfrow = c(2,2)) 
plot(m1) 

AIC(m1)
BIC(m1)


m2 = lm(stroop_correct ~ language * age * IQ, final_df)
summary(m2)

par(mfrow = c(2,2)) 
plot(m2) 

AIC(m2)
BIC(m2)

m3 = lm(stroop_correct~group_language * age_z * iq_z, final_df)
summary(m3)

par(mfrow = c(2,2)) 
plot(m3) 

AIC(m3)
BIC(m3)

m4 = lm(flanker_correct ~ language + age + IQ, final_df)
summary(m4)

par(mfrow = c(2,2)) 
plot(m4) 

AIC(m4)
BIC(m4)

m5 = lm(flanker_correct ~ language * age * IQ, final_df)
summary(m5)

par(mfrow = c(2,2)) 
plot(m5) 

AIC(m5)
BIC(m5)

m6 = lm(flanker_correct~group_language * age_z * iq_z, final_df)
summary(m6)

par(mfrow = c(2,2)) 
plot(m6) 

AIC(m6)
BIC(m6)

m7 = lm(backward_correct ~ language + age + IQ, final_df)
summary(m7)

par(mfrow = c(2,2)) 
plot(m7) 

AIC(m7)
BIC(m7)

m8 = lm(backward_correct ~ language * age * IQ, final_df)
summary(m8)

par(mfrow = c(2,2)) 
plot(m8) 

AIC(m8)
BIC(m8)

m9 = lm(backward_correct~group_language * age_z * iq_z, final_df)
summary(m9)

par(mfrow = c(2,2)) 
plot(m9) 

AIC(m9)
BIC(m9)
```





##Plots 
```{r}
plot1 <- final_df %>% 
  ggplot()+
  aes(x = age_z, y=flanker_correct,color=factor(group_language))+
  geom_point(size = 1) +
  ggtitle("Plot 1") + 
  geom_smooth(method = "lm") + 
  labs(color = "Language Group")+
  scale_color_manual(labels = c("NonLanguage","Language"),values = c("red","blue"))

plot2 <- final_df %>% 
  ggplot()+
  aes(x = age_z, y=stroop_correct,color=factor(group_language))+
  geom_point(size = 1) +
  ggtitle("Plot 2") + 
  geom_smooth(method = "lm") + 
  labs(color = "Language Group")+
  scale_color_manual(labels = c("NonLanguage","Language"),values = c("red","blue"))

plot3 <- final_df %>% 
  ggplot()+
  aes(x = age_z, y=backward_correct,color=factor(group_language))+
  geom_point(size = 1) +
  ggtitle("Plot 3") + 
  geom_smooth(method = "lm") + 
  labs(color = "Language Group")+
  scale_color_manual(labels = c("NonLanguage","Language"),values = c("red","blue"))

library(patchwork)
#(plot1 + plot_spacer() + plot2) / (plot_spacer() + plot3 + plot_spacer())  
plot1 / plot2  / plot3 
```

```{r}
plot4 <- final_df %>% 
  ggplot()+
  aes(x = iq_z, y=flanker_correct,color=factor(group_language))+
  geom_point(size = 1) +
  ggtitle("Plot 4") + 
  geom_smooth(method = "lm") + 
  labs(color = "Language Group")+
  scale_color_manual(labels = c("NonLanguage","Language"),values = c("red","blue"))

plot5 <- final_df %>% 
  ggplot()+
  aes(x = iq_z, y=stroop_correct,color=factor(group_language))+
  geom_point(size = 1) +
  ggtitle("Plot 5") + 
  geom_smooth(method = "lm") + 
  labs(color = "Language Group")+
  scale_color_manual(labels = c("NonLanguage","Language"),values = c("red","blue"))

plot6 <- final_df %>% 
  ggplot()+
  aes(x = iq_z, y=backward_correct,color=factor(group_language))+
  geom_point(size = 1) +
  ggtitle("Plot 6") + 
  geom_smooth(method = "lm") + 
  labs(color = "Language Group")+
  scale_color_manual(labels = c("NonLanguage","Language"),values = c("red","blue"))

library(patchwork)
plot4 + plot5 + plot6
plot_layout(ncol = 2)
```


## Background Questionnaire
```{r}
background_survey <- read.csv("~/Desktop/RStudio_QP/experiment_data/background_survey.csv", header = TRUE)
```

```{r }
str(background_survey)
background_survey$Age <- as.numeric(background_survey$Age)
background_survey_1  <- background_survey[1:57,] 

background_survey_1

#Reorganized years of experience in order on table
background_survey_1$Experience = factor(background_survey_1$Experience,levels = c('1-3 years', '4-6 years', '7-10 years', '11-15 years', '16+ years' ))


table1(~Bilingual + Age + Ethnicity + Experience | Gender , data = background_survey_1) 

table1(~Bilingual + Age+Ethnicity | Gender , data = background_survey_1,topclass = "Rtable1-grid")

table1(~Bilingual + Residence + Teaching_Level + Experience | Gender , data = background_survey_1) 


```
















